# Generated by Django 4.2.11 on 2024-04-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("biddingwheels_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver_id",
                    models.ForeignKey(
                        db_column="receiverID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="biddingwheels_app.user",
                    ),
                ),
                (
                    "sender_id",
                    models.ForeignKey(
                        db_column="senderID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="biddingwheels_app.user",
                    ),
                ),
            ],
        ),
    ]
