# Generated by Django 4.2.11 on 2024-04-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biddingwheels_app", "0002_message"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="message",
            table="Message",
        ),
    ]
